---
title: "Carbon"
author: "Vincent Bisquay Gracia"
date: "12/05/2021"
output:
  html_document: default
  word_document: default
---

# I. set up

Used pakages :

```{r setup, message=FALSE, warning=FALSE}

setwd(
  "D:/Users/181248/Documents/R")
library(magrittr)
library(cowplot)
library(ggplot2)
library(raster)
library(animation)
library(rasterVis)

```

```{r data}

BAU_input =
  "D:/Users/181248/Documents/Klamath_(CA_only)_2021 - Harvest BAU/"

Adapty_input = 
  "D:/Users/181248/Documents/Klamath_(CA_only)_2021 - Harvest Adaptability/"




```

# II. Comparison

Put 0 in the rows where there is no disturbancy

```{r mortBAU}

BAU_BDA_Tot = paste(BAU_input,"..1/bda_log.csv",sep="") %>% read.csv()
BAU_BDA = cbind(BAU_BDA_Tot$Time, BAU_BDA_Tot$TotalBiomassMortality) %>% as.data.frame()
colnames(BAU_BDA) = c("Time", "Mortality")

BAU_BDA = aggregate(BAU_BDA$Mortality, by=list(Time=BAU_BDA$Time), FUN=sum)

colnames(BAU_BDA) = c("Time", "Mortality")


for(i in (1:100)){
  if(!(i %in% BAU_BDA$Time)){
    BAU_BDA = rbind(BAU_BDA, c(i,0))
  }
}

BAU_BDA$Scenario = "BAU"

```

```{r mortAdapty}

Adapty_BDA_Tot = paste(Adapty_input,"..1/bda_log.csv",sep="") %>% read.csv()
Adapty_BDA = cbind(Adapty_BDA_Tot$Time, Adapty_BDA_Tot$TotalBiomassMortality) %>% as.data.frame()
colnames(Adapty_BDA) = c("Time", "Mortality")

Adapty_BDA = aggregate(Adapty_BDA$Mortality, by=list(Time=Adapty_BDA$Time), FUN=sum)

colnames(Adapty_BDA) = c("Time", "Mortality")

for(i in (1:100)){
  if(!(i %in% Adapty_BDA$Time)){
    Adapty_BDA = rbind(Adapty_BDA, c(i,0))
  }
}

Adapty_BDA$Scenario = "Adapty_V1"

```

```{r mortAdapty2}

Adapty_BDA_Tot2 = paste(Adapty_input,"..2/bda_log.csv",sep="") %>% read.csv()
Adapty_BDA2 = cbind(Adapty_BDA_Tot2$Time, Adapty_BDA_Tot2$TotalBiomassMortality) %>% as.data.frame()
colnames(Adapty_BDA2) = c("Time", "Mortality")

Adapty_BDA2 = aggregate(Adapty_BDA2$Mortality, by=list(Time=Adapty_BDA2$Time), FUN=sum)

colnames(Adapty_BDA2) = c("Time", "Mortality")

for(i in (1:100)){
  if(!(i %in% Adapty_BDA2$Time)){
    Adapty_BDA2 = rbind(Adapty_BDA2, c(i,0))
  }
}

Adapty_BDA2$Scenario = "Adapty_V2"

```

```{r look1}
pInsect1 = ggplot(BAU_BDA_Tot, aes(x=AgentName, y=TotalBiomassMortality)) +
  geom_bar(stat='identity') +
  xlab("Type of insect disturbacy") +
  ylab("Mortality in biomass") +
  ggtitle("Mortality depending on insect disturbancies") +
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 30, hjust = 1))

pInsect2 = ggplot(Adapty_BDA_Tot, aes(x=AgentName, y=TotalBiomassMortality)) +
  geom_bar(stat='identity') +
  xlab("Type of insect disturbacy") +
  ylab("Mortality in biomass") +
  ggtitle("Mortality depending on insect disturbancies") +
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 30, hjust = 1))

pInsect3 = ggplot(Adapty_BDA_Tot2, aes(x=AgentName, y=TotalBiomassMortality)) +
  geom_bar(stat='identity') +
  xlab("Type of insect disturbacy") +
  ylab("Mortality in biomass") +
  ggtitle("Mortality depending on insect disturbancies") +
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 30, hjust = 1))

plot_grid(pInsect1, pInsect2, pInsect3, labels="AUTO", ncol = 3, nrow = 1)

```

```{r look2}

BDA = rbind(BAU_BDA,Adapty_BDA,Adapty_BDA2)

ggplot(BDA, aes(x=Time, y=Mortality)) +
  geom_bar(stat='identity') +
  xlab("Type of insect disturbacy") +
  ylab("Mortality in biomass") +
  ggtitle("Mortality depending on insect disturbancies") +
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 30, hjust = 1)) +
  facet_wrap(~Scenario)

```

Non parametric test and paired => Wilcoxon Test

```{r comp}

shapiro.test(BAU_BDA$Mortality)
shapiro.test(Adapty_BDA$Mortality)
shapiro.test(Adapty_BDA2$Mortality)

Mortality_BAU = mean(BAU_BDA$Mortality)
sd_BAU = sd(BAU_BDA$Mortality)

Mortality_Adapty = mean(Adapty_BDA$Mortality)
sd_Adapty = sd(Adapty_BDA$Mortality)

Mortality_Adapty2 = mean(Adapty_BDA2$Mortality)
sd_Adapty2 = sd(Adapty_BDA2$Mortality)

data.frame("Mean Mortality by insects" = c(Mortality_BAU,Mortality_Adapty,Mortality_Adapty2), "Standard error" = c(sd_BAU,sd_Adapty,sd_Adapty2),
           row.names = c("Business as usual","adaptability","adaptability v2"))

wilcox.test(BAU_BDA$Mortality, Adapty_BDA$Mortality, paired=T)

#wilcox.test(Adapty_BDA$Mortality, Adapty_BDA2$Mortality, paired=T)

```
